version: '3'

services:
  clientgate.repository.mssql:
    image: clientgate.repository.mssql
    build:
      context: ./ClientGate.Repository/docker/sql-server/
      dockerfile: Dockerfile
    environment:
      - SA_PASSWORD=p@ssw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - db-network

  clientgate.repository.mongodb:
    image: clientgate.repository.mongodb
    build:
      context: ./ClientGate.Repository/docker/mongo-db/
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    networks:
      - db-network

  clientgate.api:
    image: clientgate.api
    build:
      context: .
      dockerfile: ClientGate.Api/Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - clientgate.repository.mssql
    networks:
      - db-network
      - front-network
    environment:
      - CONNECTIONSTRING=Password=p@ssw0rd;Persist Security Info=True;User ID=sa;Initial Catalog=NL_CLIENTGATE;Data Source=clientgate.repository.mssql

  clientgate.broker:
    image: clientgate.broker
    build:
      context: .
      dockerfile: ClientGate.Broker/Dockerfile
    ports:
      - "8080:80"
    networks:
      - front-network

networks:
  front-network:
  db-network: